[package]
name = "mavlink2rest"
version = "0.1.0"
description = "A simple REST API for MAVLink"
license = "MIT"
authors = ["Patrick José Pereira <patrickelectric@gmail.com>"]
edition = "2018"

[[bin]]
bench = false
path = "src/main.rs"
name = "mavlink2rest"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.8.3"
actix-web = "1.0.8"
clap = "2.31.2"
inner = "0.1.1"
lazy_static = "1.4.0"
mavlink = "0.6"
rustc-serialize = "0.3.24"
serde_json = "1.0.41"
