[package]
name = "mavlink2rest"
version = "0.1.0"
authors = ["Patrick José Pereira <patrickelectric@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.8.3"
actix-web = "1.0.8"
clap = "2.31.2"
inner = "0.1.1"
lazy_static = "1.4.0"
rustc-serialize = "0.3.24"
serde_json = "1.0.41"

# It's not available in a release yet
mavlink = { git = "https://github.com/mavlink/rust-mavlink", branch = "master" }
